include:
  - project: "agilefabric/france/phenix/ci-gitlab/python-ci"
    ref: v1.4.2
    file: "ci/python/python.gitlab-ci.yml"

variables:
  APP: kafka-agentic-platform
  APP_KIND: "ai-agents"
  PYTHON_VERSION: "3.11"
  KUBERNETES_CPU_REQUEST: "1"
  KUBERNETES_CPU_LIMIT: "2"
  KUBERNETES_MEMORY_REQUEST: "4Gi"
  KUBERNETES_MEMORY_LIMIT: "4Gi"
  AUTOMATIC_VERSIONING: "true"
  # Empêche la coupure de connexion par le pare-feu Carrefour en sérialisant les téléchargements
  UV_CONCURRENT_DOWNLOADS: "1"

# Génère dynamiquement le lockfile depuis Artifactory
before_script:
  - uv lock

check-lockfile:
  rules:
    - when: never

# Surcharge du linter pour exécuter uniquement le ruff check statique
lint-format:
  before_script: []
  script:
    - pip install ruff==0.4.0
    - ruff check .

# Laisse pytest s'exécuter sur TOUTES les branches (MR et main), mais uniquement pour les tests unitaires isolés !
pytest:
  before_script:
    - uv lock
  script:
    - uv sync --all-extras
    - uv run pytest tests/unit/ --junitxml=report.xml --cov=core --cov-report=term --cov-report=xml

# Surcharge du job de release pour ré-injecter les credentials Artifactory du pipeline
python-semantic-release:
  variables:
    UV_INDEX_CARREFOUR_USERNAME: $AF_JFROG_USERNAME
    UV_INDEX_CARREFOUR_PASSWORD: $AF_JFROG_PASSWORD

# Réserve le build d'image de production et sa publication pour la branche main après merge
docker-build:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  before_script:
    - uv lock
  script:
    - |
        DOCKER_TAG=$(grep -m 1 "^version = " pyproject.toml | tr -d '"' | tr -d "'" | cut -d "=" -f 2 | xargs)
        DOCKER_IMAGE="${DOCKER_REGISTRY}/phenix/${APP_KIND}/${DOCKER_IMAGE_NAME}:${DOCKER_TAG}"
        /kaniko/executor \
          --cache=true                                          \
          --dockerfile "deploy/Dockerfile.backend"              \
          --context "$(pwd)"                                    \
          --target "prod" \
          --destination "${DOCKER_IMAGE}"
