"""Format audit.md sections into Jira wiki markup for the Post-to-Jira feature.

Spec 001 T057 — extracts executive summary + ranked hypotheses table,
converts Markdown to Jira wiki format, appends platform footer.
"""

from __future__ import annotations

import re


_FOOTER = "\n----\n_Generated by kafka-agentic-platform v0 (read-only audit, autonomy L2)_\n"

# Regex to capture the executive summary block (3 lines after the section header).
_SUMMARY_RE = re.compile(
    r"##\s*Executive\s*Summary\s*\n+((?:.+\n?){1,3})",
    re.IGNORECASE,
)

# Regex to extract a Markdown table (header + separator + rows).
_TABLE_RE = re.compile(
    r"(\|.+\|\s*\n\|[-| :]+\|\s*\n(?:\|.+\|\s*\n)+)",
    re.MULTILINE,
)

# Rank column content like "1", "2" etc.
_HYPOTHESES_SECTION_RE = re.compile(
    r"##\s*Ranked\s*Hypotheses\s*\n+(.*?)(?=\n##|\Z)",
    re.IGNORECASE | re.DOTALL,
)


def format_audit_for_jira(audit_md: str) -> str:
    """Convert audit.md to Jira wiki markup suitable for a Jira comment.

    Returns a string with:
      - Executive summary (plain text, 3 lines)
      - Ranked hypotheses as a Jira table
      - Platform footer
    """
    sections: list[str] = []

    # ── Executive Summary ─────────────────────────────────────────────────────
    summary_match = _SUMMARY_RE.search(audit_md)
    if summary_match:
        summary_text = summary_match.group(1).strip()
        sections.append(f"h3. Executive Summary\n\n{summary_text}")
    else:
        # Fallback: first non-empty paragraph
        first_para = _first_paragraph(audit_md)
        if first_para:
            sections.append(f"h3. Summary\n\n{first_para}")

    # ── Ranked Hypotheses ─────────────────────────────────────────────────────
    hyp_match = _HYPOTHESES_SECTION_RE.search(audit_md)
    if hyp_match:
        hyp_block = hyp_match.group(1).strip()
        table_match = _TABLE_RE.search(hyp_block)
        if table_match:
            jira_table = _md_table_to_jira(table_match.group(1))
            sections.append(f"h3. Ranked Hypotheses\n\n{jira_table}")

    # ── Conflict banner ───────────────────────────────────────────────────────
    if "⚠ CONFLICT" in audit_md or "CONFLICT DETECTED" in audit_md:
        sections.append("{warning}Conflicting hypotheses detected — see full audit for details.{warning}")

    # ── Partial audit warning ─────────────────────────────────────────────────
    if "PARTIAL AUDIT" in audit_md:
        sections.append("{warning}Partial audit — some expert agents failed to produce output.{warning}")

    body = "\n\n".join(sections)
    return body + _FOOTER


def _first_paragraph(text: str) -> str:
    """Return the first non-heading, non-empty paragraph."""
    for line in text.splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith("#") and not stripped.startswith("|"):
            return stripped
    return ""


def _md_table_to_jira(md_table: str) -> str:
    """Convert a Markdown table to Jira wiki table syntax.

    Markdown:  | Col1 | Col2 |
               | ---- | ---- |
               | val  | val  |

    Jira:      || Col1 || Col2 ||
               | val | val |
    """
    lines = [l.strip() for l in md_table.strip().splitlines() if l.strip()]
    if len(lines) < 2:
        return md_table

    result: list[str] = []
    for i, line in enumerate(lines):
        if not line.startswith("|"):
            continue
        # separator row — skip
        if re.match(r"^\|[-| :]+\|$", line):
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        if i == 0:
            # Header row → || header ||
            result.append("|| " + " || ".join(cells) + " ||")
        else:
            result.append("| " + " | ".join(cells) + " |")

    return "\n".join(result)
