"""SQLAlchemy ORM models for kafka-agentic-platform.

All tables are defined here so Alembic autogenerate picks them up.
Use `core.db.get_session()` to obtain an async session.
"""

from __future__ import annotations

import uuid
from datetime import date, datetime, timezone

import sqlalchemy as sa
from sqlalchemy import (
    Boolean,
    Date,
    DateTime,
    ForeignKey,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from pgvector.sqlalchemy import Vector
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


def _now() -> datetime:
    return datetime.now(timezone.utc)


class Base(DeclarativeBase):
    pass


class MissionsSeq(Base):
    """Atomic MISSION_ID sequence counter (spec 003 FR-008)."""

    __tablename__ = "missions_seq"
    __table_args__ = (
        UniqueConstraint("tenant", "env", "type", "subject", "mission_date"),
    )

    # Composite PK mirrors the UNIQUE constraint
    tenant: Mapped[str] = mapped_column(String, primary_key=True)
    env: Mapped[str] = mapped_column(String, primary_key=True)
    type: Mapped[str] = mapped_column(String, primary_key=True)
    subject: Mapped[str] = mapped_column(String, primary_key=True)
    mission_date: Mapped[date] = mapped_column(Date(), primary_key=True)
    seq: Mapped[int] = mapped_column(Integer, nullable=False, default=1)


class Trigger(Base):
    """Incoming event from Jira, alertmanager, or Care."""

    __tablename__ = "triggers"
    __table_args__ = (
        UniqueConstraint("tenant", "source", "external_id"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    tenant: Mapped[str] = mapped_column(String, nullable=False)
    source: Mapped[str] = mapped_column(String, nullable=False)  # jira | alertmanager | care
    external_id: Mapped[str] = mapped_column(String, nullable=False)
    payload: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)
    matched: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    mission_id: Mapped[str | None] = mapped_column(String, nullable=True)
    received_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_now
    )
    processed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    claimed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    claimed_by: Mapped[str | None] = mapped_column(String, nullable=True)
    attempts: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    last_error: Mapped[str | None] = mapped_column(String, nullable=True)


class Mission(Base):
    """One isolated mission per (tenant, env, type, subject) occurrence."""

    __tablename__ = "missions"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    mission_id: Mapped[str] = mapped_column(String, nullable=False, unique=True)
    tenant: Mapped[str] = mapped_column(String, nullable=False)
    env: Mapped[str] = mapped_column(String, nullable=False)
    cluster: Mapped[str] = mapped_column(String, nullable=False, default="")
    type: Mapped[str] = mapped_column(String, nullable=False)
    subject: Mapped[str] = mapped_column(String, nullable=False)
    status: Mapped[str] = mapped_column(String, nullable=False, default="OPEN")
    autonomy_level: Mapped[str] = mapped_column(String, nullable=False, default="L2")
    trigger_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("triggers.id"), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_now
    )
    closed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    mission_metadata: Mapped[dict] = mapped_column("metadata", JSONB, nullable=False, default=dict)


class Audit(Base):
    """Ranked-hypotheses audit.md generated by evidence_consolidator."""

    __tablename__ = "audits"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    mission_id: Mapped[str] = mapped_column(
        String, ForeignKey("missions.mission_id"), nullable=False
    )
    agent: Mapped[str] = mapped_column(String, nullable=False, default="")
    content_md: Mapped[str] = mapped_column(Text, nullable=False, default="")
    posted_jira: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    jira_comment_id: Mapped[str | None] = mapped_column(String, nullable=True)
    brief_path: Mapped[str | None] = mapped_column(Text, nullable=True)
    finalized_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    kb_card_slug: Mapped[str | None] = mapped_column(String, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_now
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_now, onupdate=_now
    )


class AgentOutput(Base):
    """Intermediate Markdown output from a single expert agent."""

    __tablename__ = "agent_outputs"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    mission_id: Mapped[str] = mapped_column(
        String, ForeignKey("missions.mission_id"), nullable=False
    )
    agent: Mapped[str] = mapped_column(String, nullable=False)
    output_json: Mapped[dict] = mapped_column(JSONB, nullable=False, default=dict)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_now
    )


class FilterRule(Base):
    """Runtime-editable filter rule — see spec 002."""

    __tablename__ = "filter_rules"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    tenant: Mapped[str] = mapped_column(String, nullable=False)
    scope: Mapped[str] = mapped_column(String, nullable=False)  # jira | alertmanager | care
    name: Mapped[str] = mapped_column(String, nullable=False)
    enabled: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    priority: Mapped[int] = mapped_column(Integer, nullable=False, default=100)
    poll_interval_seconds: Mapped[int] = mapped_column(Integer, nullable=False, default=60)
    criteria: Mapped[dict] = mapped_column(JSONB, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_now
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_now, onupdate=_now
    )
    created_by: Mapped[str | None] = mapped_column(String, nullable=True)


class FilterMatchLog(Base):
    """Audit log of every trigger evaluation against a rule."""

    __tablename__ = "filter_match_log"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    rule_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("filter_rules.id"), nullable=True
    )
    trigger_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("triggers.id"), nullable=True
    )
    matched: Mapped[bool] = mapped_column(Boolean, nullable=False)
    matched_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_now
    )
    reason: Mapped[str | None] = mapped_column(Text, nullable=True)


class InfrastructureEnv(Base):
    """Persists dynamic environment configurations (CRUD via UI)."""

    __tablename__ = "infrastructure_envs"
    __table_args__ = (UniqueConstraint("tenant", "slug"),)

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    tenant: Mapped[str] = mapped_column(String, nullable=False)
    slug: Mapped[str] = mapped_column(String, nullable=False)  # e.g., 'preprod'
    display_name: Mapped[str] = mapped_column(String, nullable=False)
    badge_color: Mapped[str] = mapped_column(String, nullable=False, default="gray")
    clusters: Mapped[list[str]] = mapped_column(JSONB, nullable=False)
    kubeconfig: Mapped[str] = mapped_column(String, nullable=False)
    kube_context: Mapped[str] = mapped_column(String, nullable=False, default="")
    kubeconfig_content: Mapped[str] = mapped_column(Text, nullable=False, default="")
    target_gsa_email: Mapped[str] = mapped_column(Text, nullable=False, default="")
    kafka_namespace: Mapped[str] = mapped_column(String, nullable=False, default="")
    prom_url: Mapped[str] = mapped_column(String, nullable=False)
    alertmanager_url: Mapped[str] = mapped_column(String, nullable=False, default="")
    proxy_url: Mapped[str] = mapped_column(Text, nullable=False, default="")
    proxy_user: Mapped[str] = mapped_column(Text, nullable=False, default="")
    proxy_pass: Mapped[str] = mapped_column(Text, nullable=False, default="")
    vm_url: Mapped[str] = mapped_column(String, nullable=False, default="")
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_now
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_now, onupdate=_now
    )


class PlatformSetting(Base):
    """Global platform settings (Master GSA key, etc.)."""

    __tablename__ = "platform_settings"

    key: Mapped[str] = mapped_column(String, primary_key=True)
    value: Mapped[str] = mapped_column(Text, nullable=False)


class SystemAudit(Base):
    """General purpose audit trail for platform actions (deletions, etc.)."""

    __tablename__ = "system_audit"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    action: Mapped[str] = mapped_column(String, nullable=False)  # e.g. "DELETE_MISSION", "DELETE_KB_CARD"
    resource_type: Mapped[str] = mapped_column(String, nullable=False)  # e.g. "MISSION", "KB_CARD"
    resource_id: Mapped[str] = mapped_column(String, nullable=False)
    audit_metadata: Mapped[dict] = mapped_column("audit_metadata", JSONB, nullable=False, default=dict)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_now
    )
    created_by: Mapped[str | None] = mapped_column(String, nullable=True)


class KBChunk(Base):
    """A segment of a KB card, stored with its embedding."""

    __tablename__ = "kb_chunks"
    __table_args__ = (UniqueConstraint("kb_slug", "chunk_index"),)

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    kb_slug: Mapped[str] = mapped_column(String, nullable=False)
    chunk_index: Mapped[int] = mapped_column(Integer, nullable=False)
    chunk_text: Mapped[str] = mapped_column(Text, nullable=False)
    embedding: Mapped[Vector] = mapped_column(Vector(384))
    chunk_metadata: Mapped[dict | None] = mapped_column("metadata", JSONB, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=sa.text("now()")
    )


class AuditChunk(Base):
    """A segment of a mission audit, stored with its embedding."""

    __tablename__ = "audit_chunks"
    __table_args__ = (UniqueConstraint("mission_id", "chunk_index"),)

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    mission_id: Mapped[str] = mapped_column(String, nullable=False)
    chunk_index: Mapped[int] = mapped_column(Integer, nullable=False)
    chunk_text: Mapped[str] = mapped_column(Text, nullable=False)
    embedding: Mapped[Vector] = mapped_column(Vector(384))
    chunk_metadata: Mapped[dict | None] = mapped_column("metadata", JSONB, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=sa.text("now()")
    )
