configs:
  "docker.io":
    tls:
      insecure_skip_verify: true
  "quay.io":
    tls:
      insecure_skip_verify: true
  "ghcr.io":
    tls:
      insecure_skip_verify: true
  "registry-1.docker.io":
    tls:
      insecure_skip_verify: true
