"""add alertmanager_url and gcp_sa_key to infrastructure_envs

Revision ID: 1e9f1701d1a3
Revises: a081a3724e15
Create Date: 2026-05-14 21:27:07.899474
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e9f1701d1a3'
down_revision: Union[str, None] = 'a081a3724e15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('infrastructure_envs', sa.Column('alertmanager_url', sa.String(), nullable=False, server_default=''))
    op.alter_column('platform_settings', 'key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('platform_settings', 'key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('infrastructure_envs', 'alertmanager_url')
    # ### end Alembic commands ###
