"""add target_gsa_email to infrastructure_envs

Revision ID: 57f19c05fb6a
Revises: e2723fb4f1cc
Create Date: 2026-05-14 10:00:00.000000

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57f19c05fb6a'
down_revision: Union[str, None] = 'e2723fb4f1cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('infrastructure_envs', sa.Column('target_gsa_email', sa.Text(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('infrastructure_envs', 'target_gsa_email')
    # ### end Alembic commands ###
