"""add infrastructure_envs table

Revision ID: a343369a80c4
Revises: f8368a6895bb
Create Date: 2026-05-13 03:00:00.000000
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a343369a80c4'
down_revision: Union[str, None] = 'f8368a6895bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('infrastructure_envs',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tenant', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('badge_color', sa.String(), nullable=False),
    sa.Column('clusters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('kubeconfig', sa.String(), nullable=False),
    sa.Column('kafka_namespace', sa.String(), nullable=False),
    sa.Column('prom_url', sa.String(), nullable=False),
    sa.Column('vm_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant', 'slug')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('infrastructure_envs')
    # ### end Alembic commands ###
