"""sync_models

Revision ID: ba677a1f0fab
Revises: d1e510acb17b
Create Date: 2026-05-20 10:49:35.314845
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'ba677a1f0fab'
down_revision: Union[str, None] = 'd1e510acb17b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_chunks', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('audit_chunks', 'embedding',
               existing_type=Vector(384),
               nullable=False)
    op.alter_column('audit_chunks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_audit_chunks_embedding'), table_name='audit_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_audit_chunks_metadata'), table_name='audit_chunks', postgresql_using='gin')
    op.drop_column('audit_chunks', 'chunk_metadata')
    op.add_column('audits', sa.Column('kb_card_slug', sa.String(), nullable=True))
    op.add_column('infrastructure_envs', sa.Column('kube_context', sa.String(), nullable=False))
    op.add_column('infrastructure_envs', sa.Column('kubeconfig_content', sa.Text(), nullable=False))
    op.add_column('infrastructure_envs', sa.Column('proxy_url', sa.Text(), nullable=False))
    op.add_column('infrastructure_envs', sa.Column('proxy_user', sa.Text(), nullable=False))
    op.add_column('infrastructure_envs', sa.Column('proxy_pass', sa.Text(), nullable=False))
    op.add_column('kb_chunks', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('kb_chunks', 'embedding',
               existing_type=Vector(384),
               nullable=False)
    op.alter_column('kb_chunks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_kb_chunks_embedding'), table_name='kb_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_column('kb_chunks', 'chunk_metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kb_chunks', sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_kb_chunks_embedding'), 'kb_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('kb_chunks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('kb_chunks', 'embedding',
               existing_type=Vector(384),
               nullable=True)
    op.drop_column('kb_chunks', 'metadata')
    op.drop_column('infrastructure_envs', 'proxy_pass')
    op.drop_column('infrastructure_envs', 'proxy_user')
    op.drop_column('infrastructure_envs', 'proxy_url')
    op.drop_column('infrastructure_envs', 'kubeconfig_content')
    op.drop_column('infrastructure_envs', 'kube_context')
    op.drop_column('audits', 'kb_card_slug')
    op.add_column('audit_chunks', sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_audit_chunks_metadata'), 'audit_chunks', ['chunk_metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_audit_chunks_embedding'), 'audit_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('audit_chunks', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_chunks', 'embedding',
               existing_type=Vector(384),
               nullable=True)
    op.drop_column('audit_chunks', 'metadata')
    # ### end Alembic commands ###
