"""add gcp_sa_key to infrastructure_envs

Revision ID: e2723fb4f1cc
Revises: a343369a80c4
Create Date: 2026-05-13 03:10:00.000000

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2723fb4f1cc'
down_revision: Union[str, None] = 'a343369a80c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('infrastructure_envs', sa.Column('gcp_sa_key', sa.Text(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('infrastructure_envs', 'gcp_sa_key')
    # ### end Alembic commands ###
