"""rename_system_audit_metadata

Revision ID: f8368a6895bb
Revises: 300f462724b6
Create Date: 2026-05-12 16:05:19.508487
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8368a6895bb'
down_revision: Union[str, None] = '300f462724b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_audit', sa.Column('audit_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_column('system_audit', 'metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_audit', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('system_audit', 'audit_metadata')
    # ### end Alembic commands ###
